FROM golang:1.23.4-alpine3.21

WORKDIR /app

RUN apk add --no-cache bash git

RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

ENV PATH="go/bin:$PATH"
