services:
  db:
    image: postgres:15
    container_name: chirpy_db
    # Expose Postgres on host port 5432
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    container_name: chirpy_migrate
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      sh -c "
        echo 'Running sqlc generate...' &&
        sqlc generate &&
        echo 'Running goose up...' &&
        goose -dir=./sql/schema postgres $DOCKER_DB_URL up
      "

volumes:
  db-data:
